import {
  ColorsBgDark,
  ColorsBgMain,
  ColorsBrandPrimaryContrastText,
  ColorsBrandPrimaryDark,
  ColorsBrandPrimaryMain,
  ColorsBrandSecondaryMain,
  ColorsErrorContrastText,
  ColorsErrorMain,
  ColorsInfoContrastText,
  ColorsInfoMain,
  ColorsSuccessContrastText,
  ColorsSuccessMain,
  ColorsSurfaceDark,
  ColorsSurfaceMain,
  ColorsTextPrimary,
  ColorsWarningContrastText,
  ColorsWarningMain,
} from "@mat4/theme";

export const lightTheme =  {
  dark: false,

  colors: {
    background: ColorsBgMain,
    surface: ColorsSurfaceMain,
    primary: ColorsBrandPrimaryMain,
    "primary-darken-1": ColorsBrandPrimaryDark,
    secondary: ColorsBrandSecondaryMain,
    error: ColorsErrorMain,
    info: ColorsInfoMain,
    success: ColorsSuccessMain,
    warning: ColorsWarningMain,
    "on-primary": ColorsBrandPrimaryContrastText,
    "on-error": ColorsErrorContrastText,
    "on-warning": ColorsWarningContrastText,
    "on-info": ColorsInfoContrastText,
    "on-success": ColorsSuccessContrastText,
    "on-surface": ColorsTextPrimary,
    "on-background": ColorsTextPrimary,
  },
}

export const darkTheme = {
  dark: true,
  colors: {
    background: ColorsBgDark,
    surface: ColorsSurfaceDark,
    primary: ColorsBrandPrimaryMain,
    "primary-darken-1": ColorsBrandPrimaryDark,
    secondary: ColorsBrandSecondaryMain,
    error: ColorsErrorMain,
    info: ColorsInfoMain,
    success: ColorsSuccessMain,
    warning: ColorsWarningMain,
    "on-primary": ColorsBrandPrimaryContrastText,
    "on-error": ColorsErrorContrastText,
    "on-warning": ColorsWarningContrastText,
    "on-info": ColorsInfoContrastText,
    "on-success": ColorsSuccessContrastText,
    "on-surface": ColorsTextPrimary,
    "on-background": ColorsTextPrimary,
  },
};